# Spring properties
spring:
  application:
     name: backend-service
  datasource:
    url: jdbc:mysql://139.59.175.35:3306/digital-music-develop
    username: manager
    password: root
    driver-class-authority: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
hibernate:
  hbm2ddl:
    auto: validate
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.sprouts-project.com:8761/eureka/


# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

logging:
  level:
    ROOT: INFO